name: web3_universal_aa
description: ERC-4337 Account Abstraction support for Web3 Universal SDK.
version: 0.1.1
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/aa
topics:
  - web3
  - ethereum
  - account-abstraction
  - erc-4337

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../core
  web3_universal_client:
    path: ../client
  web3_universal_signer:
    path: ../signer
  web3_universal_contract:
    path: ../contract
  web3_universal_crypto:
    path: ../crypto
  web3_universal_abi:
    path: ../abi

  web3_universal_provider: ^0.1.0+1
dev_dependencies:
  test: ^1.24.0
