name: dart_web3_polkadot
description: Polkadot/Substrate blockchain extension
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.0
dependencies:
  dart_web3_core:
    path: ../../core
  dart_web3_crypto:
    path: ../../crypto
  dart_web3_signer:
    path: ../../signer

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
