name: web3_universal_polkadot
description: Polkadot/Substrate blockchain extension for Web3 Universal SDK.
version: 0.1.1
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/extensions/polkadot
topics:
  - web3
  - polkadot
  - substrate
  - blockchain

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../../core
  web3_universal_crypto:
    path: ../../crypto
  web3_universal_signer:
    path: ../../signer

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
