name: web3_universal_crypto
description: Cryptographic primitives for Web3 Universal SDK - Ed25519, Schnorr, and Secp256k1.
version: 0.2.0
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/crypto
topics:
  - web3
  - cryptography
  - ed25519
  - schnorr
  - bitcoin
  - solana

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../core
  convert: ^3.1.1
  pointycastle: ^3.9.1


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependency_overrides:
  web3_universal_core:
    path: ../core
