name: web3_universal_bitcoin
description: Bitcoin blockchain extension for Web3 Universal SDK. Supports P2PKH, P2SH, P2TR (Taproot) and PSBT.
version: 0.1.1
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/extensions/bitcoin
topics:
  - web3
  - bitcoin
  - blockchain

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core: ^0.1.1
  web3_universal_crypto: ^0.2.0
  web3_universal_signer: ^0.1.1
  bitcoin_base: ^6.0.0

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
