name: example_cli
description: Command-line wallet demo for web3_universal SDK
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  web3_universal_crypto: ^0.2.0
  web3_universal_chains: ^0.1.0+1
  web3_universal_client: ^0.1.1+1
  web3_universal_provider: ^0.1.0+1
  web3_universal_signer: ^0.1.1
  web3_universal_core: ^0.1.1
  web3_universal_utxo: ^0.1.1
  http: ^1.2.0
  bip39: ^1.0.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
