name: example_cli
description: Command-line wallet demo for web3_universal SDK
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  web3_universal_crypto:
    path: ../packages/crypto
  web3_universal_chains:
    path: ../packages/chains
  web3_universal_client:
    path: ../packages/client
  web3_universal_provider:
    path: ../packages/provider
  web3_universal_signer:
    path: ../packages/signer
  web3_universal_core:
    path: ../packages/core
  web3_universal_utxo:
    path: ../packages/utxo
  http: ^1.2.0
  bip39: ^1.0.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
