name: dart_web3_utxo
description: Shared UTXO chain logic for Bitcoin, Litecoin, Dogecoin, etc.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  dart_web3_core:
    path: ../core
  dart_web3_crypto:
    path: ../crypto

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
  convert: any
