name: dart_web3_price
description: Price service for cryptocurrency
version: 0.1.0
environment:
  sdk: ^3.6.0
dependencies:
  dart_web3_core:
    path: ../core
  http: ^1.1.0

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
