name: web3_universal_mev
description: MEV (Maximal Extractable Value) support for Web3 Universal SDK.
version: 0.1.1
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/mev
topics:
  - web3
  - ethereum
  - mev
  - flashbots

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../core
  web3_universal_provider:
    path: ../provider
  web3_universal_signer:
    path: ../signer

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
