name: dart_web3_solana
description: Solana blockchain extension
version: 0.1.0
publish_to: none
environment:
  sdk: ^3.6.0
dependencies:
  dart_web3_core:
    path: ../../core
  dart_web3_crypto:
    path: ../../crypto
  dart_web3_signer:
    path: ../../signer
  dart_web3_provider:
    path: ../../provider
  http: ^1.1.0

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
