name: web3_universal_ton
description: TON blockchain support library for Web3 Universal SDK. Supports standard wallet v3/v4 and cell serialization.
version: 0.1.1
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/extensions/ton
topics:
  - web3
  - ton
  - blockchain

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core: ^0.1.1
  web3_universal_crypto: ^0.2.0
  web3_universal_signer: ^0.1.1
  web3_universal_chains: ^0.1.0+1
  web3_universal_provider: ^0.1.0+1
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
