name: dart_web3_ton
description: TON blockchain extension
version: 0.1.0
environment:
  sdk: ^3.6.0
dependencies:
  dart_web3_core:
    path: ../../core
  dart_web3_crypto:
    path: ../../crypto
  dart_web3_signer:
    path: ../../signer

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
  dart_web3_crypto:
