name: dart_web3_swap
description: DEX aggregation and swap services for Dart Web3 SDK
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_web3_core:
    path: ../core
  dart_web3_client:
    path: ../client
  dart_web3_contract:
    path: ../contract
  http: ^1.1.0

dev_dependencies:
  test: ^1.24.0

topics:
  - blockchain
  - ethereum
  - web3
  - defi
  - swap