name: web3_universal_abi
description: Ethereum Contract ABI encoding and decoding for Web3 Universal SDK.
version: 0.1.1

homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/abi
topics:
  - web3
  - ethereum
  - abi
  - solidity

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../core
  convert: ^3.1.1
  web3_universal_crypto:
    path: ../crypto
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0