name: web3_universal
description: A comprehensive pure Dart Web3 SDK - meta-package that re-exports all modules
publish_to: none
version: 0.1.0
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/web3_universal

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../packages/core
  web3_universal_crypto:
    path: ../packages/crypto
  web3_universal_abi:
    path: ../packages/abi
  web3_universal_provider:
    path: ../packages/provider
  web3_universal_signer:
    path: ../packages/signer
  web3_universal_chains:
    path: ../packages/chains
  web3_universal_client:
    path: ../packages/client
  web3_universal_contract:
    path: ../packages/contract
  web3_universal_events:
    path: ../packages/events
  web3_universal_multicall:
    path: ../packages/multicall
  web3_universal_ens:
    path: ../packages/ens
  web3_universal_aa:
    path: ../packages/aa
  web3_universal_reown:
    path: ../packages/reown
  web3_universal_swap:
    path: ../packages/swap
  web3_universal_bridge:
    path: ../packages/bridge
  web3_universal_nft:
    path: ../packages/nft
  web3_universal_staking:
    path: ../packages/staking
  web3_universal_history:
    path: ../packages/history
  web3_universal_price:
    path: ../packages/price
  web3_universal_dapp:
    path: ../packages/dapp
  web3_universal_debug:
    path: ../packages/debug
  web3_universal_mev:
    path: ../packages/mev
  web3_universal_solana:
    path: ../packages/extensions/solana
  web3_universal_polkadot:
    path: ../packages/extensions/polkadot
  web3_universal_tron:
    path: ../packages/extensions/tron
  web3_universal_ton:
    path: ../packages/extensions/ton
  web3_universal_bitcoin:
    path: ../packages/extensions/bitcoin
  web3_universal_bc_ur:
    path: ../packages/hardware/bc_ur
  web3_universal_keystone:
    path: ../packages/hardware/keystone
  web3_universal_ledger:
    path: ../packages/hardware/ledger
  web3_universal_trezor:
    path: ../packages/hardware/trezor
  web3_universal_mpc:
    path: ../packages/hardware/mpc

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
