name: web3_universal
description: A comprehensive pure Dart Web3 SDK - meta-package that re-exports all modules
version: 0.1.0
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/web3_universal

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core: ^0.1.1
  web3_universal_crypto: ^0.2.0
  web3_universal_abi: ^0.1.1
  web3_universal_provider: ^0.1.0+1
  web3_universal_signer: ^0.1.1
  web3_universal_chains: ^0.1.0+1
  web3_universal_client: ^0.1.1+1
  web3_universal_contract: ^0.1.0+1
  web3_universal_events: ^0.1.0+2
  web3_universal_multicall: ^0.1.0+2
  web3_universal_ens: ^0.1.1+1
  web3_universal_aa: ^0.1.1+1
  web3_universal_reown: ^0.1.1
  web3_universal_swap: ^0.1.0+2
  web3_universal_bridge: ^0.1.0+2
  web3_universal_nft: ^0.1.1+1
  web3_universal_staking: ^0.1.1+1
  web3_universal_history: ^0.1.1+1
  web3_universal_price: ^0.1.1
  web3_universal_dapp: ^0.1.1+1
  web3_universal_debug: ^0.1.1
  web3_universal_mev: ^0.1.1
  web3_universal_solana: ^0.1.1
  web3_universal_polkadot: ^0.1.1
  web3_universal_tron: ^0.1.1
  web3_universal_ton: ^0.1.1
  web3_universal_bitcoin: ^0.1.1
  web3_universal_bc_ur: ^0.1.0+1
  web3_universal_keystone: ^0.1.0+1
  web3_universal_ledger: ^0.1.0+1
  web3_universal_trezor: ^0.1.0+1
  web3_universal_mpc: ^0.1.0+1
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
