name: web3_universal_ens
description: ENS (Ethereum Name Service) resolution for Web3 Universal SDK.
version: 0.1.1+1
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/ens
topics:
  - web3
  - ethereum
  - ens
  - dns

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../core
  web3_universal_crypto:
    path: ../crypto
  web3_universal_client:
    path: ../client
  web3_universal_contract:
    path: ../contract

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
  web3_universal_abi:
    path: ../abi
  web3_universal_chains:
    path: ../chains
  web3_universal_provider:
    path: ../provider
