name: web3_universal_staking
description: Staking services for Web3 Universal SDK. Supports ETH 2.0 deposit contract and liquid staking protocols.
version: 0.1.1
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/staking
topics:
  - web3
  - ethereum
  - staking

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../core
  web3_universal_client:
    path: ../client
  web3_universal_contract:
    path: ../contract
  http: ^1.1.0

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
