name: web3_universal_events
description: Event subscription and monitoring for Ethereum in Web3 Universal SDK.
version: 0.1.0+2
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/events
topics:
  - web3
  - ethereum
  - events
  - monitoring

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../core
  web3_universal_client:
    path: ../client
  web3_universal_provider:
    path: ../provider
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
  web3_universal_chains:
    path: ../chains