name: web3_universal_multicall
description: Multicall support for batching contract calls in Web3 Universal SDK.
version: 0.1.0+2
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/multicall
topics:
  - web3
  - ethereum
  - multicall

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../core
  web3_universal_client:
    path: ../client
  web3_universal_contract:
    path: ../contract

  meta: any
  web3_universal_abi:
    path: ../abi

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
  web3_universal_chains: ^0.1.0+1
  web3_universal_provider: ^0.1.0+1
  web3_universal_signer: ^0.1.1
