name: web3_universal_nft
description: NFT services for Web3 Universal SDK - ERC-721/ERC-1155, metadata, and IPFS support.
version: 0.1.1+1
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/nft
topics:
  - web3
  - ethereum
  - nft
  - erc721
  - erc1155

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_client:
    path: ../client
  web3_universal_contract:
    path: ../contract
  web3_universal_core:
    path: ../core
  web3_universal_chains:
    path: ../chains
  http: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
