name: web3_universal_cosmos
description: Cosmos blockchain extension for Web3 Universal SDK - Protobuf, IBC, and Staking support.
version: 0.1.1
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/extensions/cosmos
topics:
  - web3
  - cosmos
  - ibc
  - blockchain

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../../core
  web3_universal_crypto:
    path: ../../crypto
  fixnum: ^1.1.0
  protobuf: ^3.1.0
  http: ^1.1.0

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
