name: web3_universal_debug
description: Debug and trace API support for Web3 Universal SDK. Includes standard Ethereum trace calls and Geth debug methods.
version: 0.1.1
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/debug
topics:
  - web3
  - ethereum
  - debug
  - tracing

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../core
  web3_universal_provider:
    path: ../provider

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
