name: web3_universal_mpc
description: MPC wallet support for Web3 Universal SDK. Implements threshold cryptography for secure key management and signing.
version: 0.1.0+1
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/hardware/mpc
topics:
  - web3
  - mpc
  - threshold-cryptography

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../../core
  web3_universal_signer:
    path: ../../signer
  web3_universal_crypto:
    path: ../../crypto

  web3_universal_abi:
    path: ../../abi
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
