name: web3_universal_aptos
description: Aptos blockchain support for Web3 Universal SDK. Supports Move VM transactions and BCS encoding.
version: 0.1.0
homepage: https://github.com/ImL1s/dart_web3
repository: https://github.com/ImL1s/dart_web3/tree/master/packages/extensions/aptos
topics:
  - web3
  - aptos
  - move
  - blockchain

environment:
  sdk: ^3.6.0

dependencies:
  web3_universal_core:
    path: ../../core
  web3_universal_crypto:
    path: ../../crypto
  web3_universal_signer:
    path: ../../signer
  web3_universal_chains:
    path: ../../chains
  web3_universal_provider:
    path: ../../provider
  http: ^1.1.0
  pointycastle: ^3.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
