name: Dart Web3 SDK CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap Workspace
        run: |
          git config --global --add safe.directory '*'
          cd dart_web3
          pwd
          ls -la
          melos list
          melos clean
          melos bootstrap --verbose

      - name: Static Analysis
        run: |
          cd dart_web3
          melos run analyze

      - name: Run Tests (All Packages)
        run: |
          cd dart_web3
          # Dynamically run tests for all packages that have a 'test' directory
          melos exec --concurrency=1 --fail-fast --dir-exists="test" -- dart test
