name: Dart Web3 SDK CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap Workspace
        run: |
          git config --global --add safe.directory '*'
          cd dart_web3
          pwd
          ls -la
          melos list
          melos clean
          echo "Testing packages/core..."
          cd packages/core && dart pub get && cd ../..
          echo "Testing packages/abi..."
          cd packages/abi && dart pub get && cd ../..
          echo "Testing packages/extensions/ton..."
          cd packages/extensions/ton && dart pub get && cd ../../..
          # melos bootstrap --verbose --no-concurrent

      - name: Static Analysis
        run: |
          cd dart_web3
          melos run analyze

      - name: Run Tests (All Packages)
        run: |
          cd dart_web3
          # Dynamically run tests for all packages that have a 'test' directory
          melos exec --concurrency=1 --fail-fast --dir-exists="test" -- dart test
